#!/bin/sh
TYPE="$1"
QUERY="$2"
BACKUPDIR="$HOME/.local/share/musicdl"
TMPDIR="$(mktemp -d /tmp/musicdl.XXXXXX)"
TRACKSFILE="$(mktemp -p "$TMPDIR" track.XXXXXX)"
[ -n "$MUSICDIR" ] || MUSICDIR="$HOME/Music"
mkdir -p "$BACKUPDIR"
case "$TYPE" in
    A|artist)
        FMT_LIST='.data[]|((.name))+" ~ "+.type+"/"+(.id|tostring)'
        TYPE="artist"
        ;;
    a|album)
        FMT_LIST='.data[]|((.artist.name+" - "+.title+.name))+" ~ "+.type+"/"+(.id|tostring)'
        TYPE="album"
        ;;
    t|track)
        FMT_LIST='.data[]|((.artist.name+" - "+.album.title+" - "+.title+.name))+" ~ "+.type+"/"+(.id|tostring)'
        TYPE="track"
        ;;
    p|playlist)
        FMT_LIST='.data[]|((.title))+" ~ "+.type+"/"+(.id|tostring)'
        TYPE="playlist"
        ;;
    url)
        URLS="$2"
        TYPE="$(echo "$URLS" | cut -d"/" -f1)"
        ;;
    *)
        printf "ERROR: Invalid type.\n" && exit
esac
if [ -z "$URLS" ]; then
    QUERY="$(echo "$QUERY" | sed 's/ /%20/g')"
    URLS="$(curl -s "https://api.deezer.com/search/$TYPE?q=$QUERY&limit=30" | jq "$FMT_LIST" | fzf --no-sort --multi | cut -d"~" -f2 | sed 's/ //g' | sed 's/"//g')"
    [ -z "$URLS" ] && exit
fi
if [ "$TYPE" = "track" ]; then 
    for URL in $URLS; do
        echo "$URL" | cut -d"/" -f2 > "$TRACKSFILE"
    done
fi
if [ "$TYPE" = "album" ]; then
    for URL in $URLS; do
        curl -s "https://api.deezer.com/$URL/tracks" | jq "(if .data then .data else .tracks.data end)[]|(.id)" > "$TRACKSFILE"
    done
fi
if [ "$TYPE" = "artist" ]; then
    for URL in $URLS; do
        curl -s "https://api.deezer.com/$URL/top?limit=15" | jq "(if .data then .data else .tracks.data end)[]|(.id)" > "$TRACKSFILE"
    done
fi
if [ "$TYPE" = "playlist" ]; then
    for URL in $URLS; do
        curl -s "https://api.deezer.com/$URL/tracks" | jq "(if .data then .data else .tracks.data end)[]|(.id)" > "$TRACKSFILE"
    done
fi
while IFS= read -r ID; do
    if [[ $(jobs -r -p | wc -l) -ge 5 ]]; then
        wait -n
    fi
    {
        DIR="$(mktemp -d -p "$TMPDIR")"
        BACKUPFILE="$ID.tar.gz"
        [ -f "$BACKUPDIR/$BACKUPFILE" ] && tar xf "$BACKUPDIR/$BACKUPFILE" -C "$DIR"
        test -f "$DIR"/*.mp3 && mp3val "$DIR"/*.mp3 | grep -q WARNING && rm -fv "$DIR"/*.mp3
        test -f "$DIR"/*.mp3 || deemix -b "320" -p "$DIR" "https://deezer.com/track/$ID"
        mp3val "$FILE" | grep -q WARNING && exit
        cd "$DIR" || exit
        FILE="$(ls "$DIR"/*.mp3)"
        TAGS="$(mid3v2 -l "$FILE")"
        echo "$TAGS" | grep -F "TXXX=replaygain_track_gain" >/dev/null ||
            mp3gain -s i "$DIR"/*.mp3
        tar caf "$BACKUPDIR/$BACKUPFILE" ./*
        ARTIST="$(echo "$TAGS" | grep -i "TPE" | sed 1q | cut -d"=" -f2 | cut -d"/" -f1 | sed "s/[:\/]/-/g" | sed 's/ *$//' | sed 's/ [ ]*/ /g' | sed 's/^ *//' | sed 's/^\.*//' | sed 's_/__g' | iconv -t ASCII)"
        DATE="$(echo "$TAGS" | grep -e "TDRC=" -e "TYER=" | cut -d"=" -f2 | sed 1q | cut -d- -f1)"
        ALBUM="$(echo "$TAGS" | grep -i "^TALB=" | cut -d"=" -f2 | sed "s/[:\/]/-/g" | sed 's/ *$//' | sed 's/ [ ]*/ /g' | sed 's/^ *//' | sed 's/^\.*//' | sed 's_/__g' | iconv -t ASCII)"
        TRACK="$(printf '%02d\n' "$(echo "$TAGS" | grep "TRCK=" | cut -d"=" -f2 | cut -d"/" -f1 | cut -d- -f1 | awk '{$0=int($0)}1')")"
        TITLE="$(echo "$TAGS" | grep  -i "^TIT2=" | cut -d"=" -f2 | sed "s/[:\/]/-/g" | sed 's/ *$//' | sed 's/ [ ]*/ /g' | sed 's/^ *//' | sed 's/^\.*//' | sed 's_/__g' | iconv -t ASCII)"
        mkdir -p "$MUSICDIR/$ARTIST/$DATE - $ALBUM"
        test -f "$MUSICDIR/$ARTIST/$DATE - $ALBUM/$TRACK - $TITLE.flac" ||
            cp -f "$FILE" "$MUSICDIR/$ARTIST/$DATE - $ALBUM/$TRACK - $TITLE.mp3" || exit
        mpc update >/dev/null
        echo "$ARTIST - $TITLE: Done"
    } &
done < "$TRACKSFILE"
wait
rm -rf "$TMPDIR"
